# This is a basic workflow to help you get started with Using Checkmarx CxFlow Action

name: CxFlow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel - this job is specifically configured to use the Checkmarx CxFlow Action
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on - Ubuntu is required as Docker is leveraged for the action
    runs-on: ubuntu-latest

    # Steps require - checkout code, run CxFlow Action, Upload SARIF report (optional)
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
      with:
        project: ${{ github.repository }}
        team: '/CxServer/SP/Company/Users'
        checkmarx_url: ${{ secrets.CHECKMARX_URL }}
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: SCA-CHampions  # <-- Insert Checkmarx CxSCA Tenant
        sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
        sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.
        break_build: false
        scanners: sca,sast
        # edit - set to full to support small demos .
        github_token: ${{secrets.GH_TOKEN}}
        preset: "High and Medium"
        incremental: false
        params: --checkmarx.incremental=false --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }}  --branch=${{ github.ref }} --cxflow.bug-tracker=GitHub --repo-url="https://github.com/bailiwick99/minitest" --cx-flow.filterSeverity --cx-flow.filterCategory
        # Upload the Report for CodeQL/Security Alerts
#   - name: Upload SARIF file
#      uses: github/codeql-action/upload-sarif@v1
#     with:
#       sarif_file: cx.sarif
